[package]
name = "worldgen-ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1"
eframe = "0.30"
egui = "0.30"
worldgen-core = { path = "../worldgen-core" }

[lints]
workspace = true
